version: '3'

services:

  app:
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/database.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/database.sql:/data/application/database.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    build:
      context: nginx
    container_name: proxy
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge 